language: node_js
node_js:
  - node
script:
  - npm run lint
  - npm test
  - npm run build
  - npm run demo
branches:
  only:
    - master
    - "/^\\d+\\.\\d+(\\.\\d+)?(-\\S*)?$/"
deploy:
  - provider: npm
    skip_cleanup: true
    email: mahesh.h4evr@gmail.com
    api_key:
      secure: yiy4Pvmc/7nKPUMW6z/mypwQta61ObHFrZ6uogv/DAwRZokJt1fFUVHuu1ks+HiCixY7Hkvw/sFuQaRdG4+e42UUfeqsfVxhCvU5WlY7U467T51mI+Uz7owBG1QcoNkb968/sJ+kho6qFT9tNeuuLStICNi7YEfaZBnxhwzlVGZIgyqloRQ1rysahMBurtGsxWlxv4blrR2C4hB5XxB3MoGNfiU8nv73IAVvYKkJApaeBl5gG16CSekGKDD9P2wcC1Ap45pu0A7idcnbcJKFMfH6eMKA+QVcvDzcEJ9I7Cz67fw65oW1pkZC48OjLJ+PO8MImuhqM129F2gias6Y/ftYhDd6u7S653BzyWAPP0j9jxi8ZJRn0gu94dBWVx6u0Rn4zIiKzQqcI+3yun+mqRncSdzq29KCzfpsY+fkWDKwhINpx7CO8OTcDRDd3U+ShsqDLGGD0JL6ZWbGH12h+/HU6nfa4TtXDGqFJ2IKvk3lmQQ/5bUrqzUrpawb/daqPLCzQc14Fzk8AQ7jG8nnzOqiGke/prIuFv1ST3uuqVUUQIxyNsZF3nleYAhI8McbNvuNkLlg1YRlEeX3lIoKFeVl58gieJu+Zfxfn1UyV2FzAYL8xyC/BkkYeuHIRoqDycbBOGD9C9N7pYqpgkbqCwX9DrqeBv1NzQc5H5r39eQ=
    on:
      tags: true
      repo: maheshsenni/react-treelist
      branch: master
  - provider: pages
    skip-cleanup: true
    github-token: "$GITHUB_TOKEN"
    local-dir: docs
    on:
      tags: true
      repo: maheshsenni/react-treelist
      branch: master
env:
  global:
    secure: Zer1L7IWvLlfoV7rejSiauDvIeOC2jFU5pM14tx2ZTUncGUgA6qy+4YPvljG++jrnH3I981Mwzq+IhGztDwESLfIGTrmok8DTZtjhAn5LIyDsnz7Z5+UUxUZME/BTMgCfwJoh/7dAL3Hxt1KgeSTM1GmcrFegTeAGkz+qKdD7m4KAWKYQ9gWFyf6elLJoZl+/vLXfXPR+OHGVpxyfABDXzJcIH2bd0aJlxr8WGlIxBUMXwBoU6w18BFta/7Fxktrpnf8vl2HYhItKClY1PJlevpcQqwfV2AcKcKxM5mXiIbrUwme5wt3qbmmNyAES2CNK1YmrpA79CnWw6iwmZPSuSO2Dy7++5pYtOVHkqOAcAgD0XgmcojGgmHML4H9evnao41OcQg+TVyk9fPGKxj7MaWEDTDje9AUmhvaMoXQwbUze89CvZMcnm3Vnid7uvOodbk2kf8usI4o5/82FaI8rUs52YkZ69loB5EDyeZQ4ZuGsJqhh29Kh3m91UbuOOFJGjmWi+/bjoe2FyFNRaq86sAgRRiRsyykMqcBFmpseCKq6xgJbOgDUC4FIwRTtjjTsBHyhHbS0PgVDJoLDmiyulFYuJa7N+PldDH5eQozNSRAuyD00xGgUjeopPdbJjCAEhVyOiDR0uZyM5z9X0mWvXV6Di7qi0WVq6OOf7kbWzQ=
